{"TuyaEmbeddedLogseq":
    [
        {"name":"mqtt",
            "logseq":[
                {"0":"System time"},
                {"9":"RSSI signal strength"},
                {"10":"DNS resolution failed, Please check the network connection.","data":"tuya"},
                {"20":"Socket connection failed, Please check the network connection.","data":"tuya"},
                {"21":"MQTT connection failed, Please check the network connection.","data":"tuya"},
                {"22":"MQTT connect wait tuya-iot-core acknowledgment failed, Please check the network connection.","data":"tuya"},
                {"30":"Subscribing to MQTT topic failed, Please check the network connection.","data":"tuya"},
                {"31":"MQTT subscribe wait tuya-iot-core acknowledgment failed, Please check the network connection.","data":"tuya"},
                {"40":"Publishing to MQTT topic failed, Please check the network connection.","data":"tuya"},
                {"41":"MQTT publish wait tuya-iot-core acknowledgment failed, Please check the network connection.","data":"tuya"},
                {"42":"MQTT publish wait tuya-iot-core acknowledgment failed after three tries, with the connection closed, Please check the network connection."},
                {"50":"Receiving MQTT message failed, Please check the network connection.","data":"tuya"},
                {"51":"Processing MQTT logic failed, Please check the network connection.","data":"tuya"},
                {"52":"Receiving MQTT connect message failed, Please check the network connection.","data":"tuya"},
                {"60":"Sending MQTT PING request failed, Please check the network connection.","data":"tuya"},
                {"61":"MQTT PING response timed out, Please check the network connection."}
            ]
        },
        {"name":"upgrade",
            "logseq":[
                {"0":"System time"},
                {"1":"Device token"},
                {"10":"OTA cofiguration verification failed, please check the OTA configuration.","data":"tuya"},
                {"12":"Get OTA cofiguration failed, please check the OTA configuration and the network connection.","data":"tuya"},
                {"13":"No silent OTA configured.","data":"tuya"},
                {"14":"Get subdevice OTA cofiguration failed, please check the OTA configuration and the network connection.","data":"tuya"},
                {"15":"Reason for OTA update failure.","data":"ext", "ext":[
                    {"40":"Update download — unknown error."},
                    {"41":"Update download — low battery."},
                    {"42":"Update download — out of storage space."},
                    {"43":"Update download — memory allocation failed."},
                    {"44":"Update download — timed out."},
                    {"45":"Update download — file HMAC does not match."},
                    {"46":"Update installation — low battery."},
                    {"47":"Update installation — memory allocation failed."},
                    {"48":"Update installation — version is not available."},
                    {"49":"Update installation — file HMAC does not match."}]},
                {"20":"Parameter validation failed on starting OTA.","data":"tuya"},
                {"21":"OTA failed to start.","data":"tuya"}
            ]
        },
        {"name":"http",
            "logseq":[
                {"0":"System time"},
                {"1":"Device token"},
                {"11":"Failed to get the URL by calling URL config interface, Please check the network connection..","data":"tuya"},
                {"20":"API name"},
                {"21":"Failed to construct the URL.","data":"tuya"},
                {"22":"Failed to construct the data.","data":"tuya"},
                {"23":"Failed to create an HTTP session, Please check the network connection..","data":"tuya"},
                {"24":"Failed to prepare HTTP request data, Please check the network connection..","data":"tuya"},
                {"25":"HTTP request failed, Please check the network connection..","data":"tuya"},
                {"30":"Failed to receive the HTTP response header, Please check the network connection..","data":"tuya"},
                {"31":"An HTTP error response is returned.","data":"tuya"},
                {"32":"Failed to receive the HTTP response.","data":"tuya"},
                {"33":"Failed to receive the parsed HTTP response.","data":"tuya"},
                {"34":"Failed to decrypt HTTP data.","data":"tuya"},
                {"35":"HTTP content error.","data":"tuya"},
                {"36":"HTTP data error.","data":"tuya"},
                {"100":"Database is damaged and restored from the cloud."}
            ]
        },
        {"name":"netcfg",
            "logseq":[
                {"0":"System time"},
                {"1":"Device token"},
                {"9":"Pairing mode"},
                {"10":"Device pairing failed.", "data":"ext", "ext":[
                    {"1":"Data format error."},
                    {"2":"Access point is not found."},
                    {"3":"Wrong password."},
                    {"4":"Cannot connect to the access point."},
                    {"5":"Failed to get the DHCP-assigned IP address."},
                    {"6":"Failed to connect to the cloud."},
                    {"7":"Failed to get the URL."},
                    {"8":"Failed to activate the device."}]},
                {"11":"Device active failed.", "data":"ext", "ext":[
                        {"2":"Failed to get the URL."},
                        {"3":"Failed to connect to the cloud."},
                        {"4":"Failed to activate the device."},
                        {"5":"Unknown error."}]},
                {"20":"Previous network status", "data":"ext", "ext":[
                    {"5":"route disconnected"},
                    {"6":"route connected, cloud disconnected"},
                    {"7":"cloud connected"}]},
                {"21":"Current network status", "data":"ext", "ext":[
                    {"5":"route disconnected"},
                    {"6":"route connected, cloud disconnected"},
                    {"7":"cloud connected"}]},
                {"22":"Exit pairing mode."},
                {"30":"Remote immediate reboot"},
                {"31":"Remote scheduled reboot"}
            ]
        },
        {"name":"svc_timer_task",
            "logseq":[
                {"0":"Result of timer execution"},
                {"1":"System time"},
                {"2":"Device token"},
                {"10":"Failed to read the timer information from the flash memory.","data":"tuya"},
                {"11":"Failed to load the timer configuration."},
                {"12":"Failed to read the timer ID from the flash memory."},
                {"20":"Failed to save the timer information to the flash memory.","data":"tuya"},
                {"30":"Failed to get the timer information from the cloud.","data":"tuya"},
                {"31":"Failed to get the timer content from the cloud.","data":"tuya"},
                {"32":"Failed to get the timer index from the cloud.","data":"tuya"},
                {"33":"Timer failed to increment."},
                {"34":"Failed to add a timer."}
            ]
        },
        {"name":"linkage_info",
            "logseq":[
                {"0":"Rule ID"},
                {"1":"Condition ID"},
                {"2":"Trigger time"},
                {"4":"Rule type", "data":"ext", "ext":[
                    {"0x0":"Local linkage"},
                    {"0x1":"LAN linkage"}]},
                {"5":"Status Condition ID"},
                {"36":"Error type", "data":"ext", "ext":[
                    {"-1":"Unknown error."},
                    {"-2":"Invalid parameter."},
                    {"-3":"Failed to allocate memory. Check if the gateway has too many sub-devices or linkages configured."},
                    {"-99":"Module initialization failed."},
                    {"-101":"Condition is not met."},
                    {"-102":"Rule ID does not exist or is not enabled."},
                    {"-103":"The rule is being updated. Try again later."},
                    {"-104":"Flow control is triggered. This might be because the linkage is run too frequently or an infinite loop occurs."},
                    {"-105":"Failed to create a thread."}]}
            ]
        },
        {"name":"linkage_local",
            "logseq":[
                {"0":"Rule ID"},
                {"1":"Condition ID"},
                {"2":"Trigger time"},
                {"4":"Rule type", "data":"ext", "ext":[
                    {"0x0":"Local linkage"},
                    {"0x1":"LAN linkage"}]},
                {"36":"Error type","data":"tuya"}
            ]
        },
        {"name":"sub_dev",
            "logseq":[
                {"1":"Device Node ID"},
                {"2":"Error occurrence time"},
                {"3":"Error type","data":"ext", "ext":[
                    {"0":"Error 0"},
                    {"1":"Error 1"},
                    {"2":"Error 2: FIB restarts."},
                    {"3":"Error 3: Restart after update."},
                    {"4":"Error 4: External I/O restarts unexpectedly."},
                    {"5":"Error 5: Restart due to low voltage, which might be caused by power-off or power supply issues."},
                    {"6":"Error 6: Watchdog restarts."},
                    {"7":"Error 7: Software proactively restarts."},
                    {"8":"Error 8: Software restarts after a crash."},
                    {"9":"Error 9: Flash memory restarts unexpectedly."},
                    {"10":"Error 10: Unrecoverable hardware restart."},
                    {"11":"Error 11: Internal CPU access error."},
                    {"12":"Error 12: Restart due to power loss, which might be caused by power-off or power supply issues."},
                    {"13":"Error 13"},
                    {"14":"Error 14"},
                    {"15":"Error 15"},
                    {"16":"Error 16: Restart"},
                    {"17":"Error 17: Disconnect"},
                    {"18":"Error 18: Proactive network leaving. Check if the user manually removes the device."},
                    {"19":"Error 19: Passive network leaving. Check if the user removes the device using the mobile app or the remote control."},
                    {"20":"Error 20: I/O exception."},
                    {"21":"Error 21: Memory leak."},
                    {"22":"Error 22: Short URL is changed."},
                    {"23":"Error 23: Factory reset is received."},
                    {"24":"Error 24: F0 command is received."},
                    {"25":"Error 25: Wake-up time is too long."},
                    {"26":"Error 26: Unexpected factory reset is received."},
                    {"27":"Error 27: Device self-recovery failed."},
                    {"28":"Error 28: Device group upgrade failed."},
                    {"101":"Error 101: No network was scanned."},
                    {"102":"Error 102: Scanning network error."},
                    {"103":"Error 103: The serial port frame format is incorrect."},
                    {"104":"Error 104: Serial ACK timeout."},
                    {"105":"Error 105: Gateway reply error."},
                    {"106":"Error 106: The MCU is always in a wakeup state."}, 
                    {"1000":"The gateway receives a message that the sub-device proactively leaves the network. Check if the user manually removes the sub-device."}]},
                {"4":"Bluetooth sub-device initiates a connection."},
                {"5":"Bluetooth sub-device initiates a disconnection."},
                {"6":"Bluetooth sub-device's connection status."},
                {"7":"Reason for Bluetooth sub-device getting disconnected."},
                {"8":"Sub-device is added successfully by drag and drop."},
                {"9":"Sub-device is unbound from gateway."},
                {"36":"Binding error type","data":"tuya"}
            ]
        },
        {"name":"zigbee",
            "logseq":[
                 {"0":"Zigbee component package version"},
                 {"1":"The gateway triggers the sub-device to leave the network"},
                 {"2":"Communication error"}
            ]
        },
        {"name":"gw_flood",
            "logseq":[
                    {"0":"Device type","data":"ext", "ext":[
                        {"1":"Bluetooth"},
                        {"3":"Zigbee"}]
                    },
                    {"1":"Flood type"},
                    {"2":"Flood times"},
                    {"3":"Flood cnts"},
                    {"4":"Device 1 details"},
                    {"5":"Device 2 details"},
                    {"97":"CCA Counters"},
                    {"98":"Start timestamp"},
                    {"99":"End timestamp"}
            ]
        },
        {"name":"gw_rst",
        "logseq":[
                {"0":"Gateway reset reason","data":"ext", "ext":[
                    {"0":"Reset caused by device removal via app in normal mode"},
                    {"1":"Reset caused by local reset in normal mode"},
                    {"2":"Reset caused by app restoring to factory settings in normal mode"},
                    {"3":"Reset caused by device removal via app in engineering mode"},
                    {"4":"Reset caused by local reset in engineering mode"},
                    {"5":"Reset caused by switching from engineering mode to normal mode"},
                    {"6":"Reset caused by switching from normal mode to engineering mode"},
                    {"7":"Reset caused by remote reboot"},
                    {"8":"Reset caused by software watchdog"}]
                },
                {"1":"Reset time"}
            ]
        },
        {"name":"cloud_storage",
            "logseq":[
                {"0":"Whether the device has the encryption key stored.","data":"tuya"},
                {"1":"Memory allocation request failed. Check the remaining memory.","data":"tuya"},
                {"2":"The size of the requested memory allocation."},
                {"3":"Reason for the failure to get orders on initialization."},
                {"4":"Type of the cloud storage order."},
                {"5":"Successful initialization."},
                {"10":"Action on the order is received."},
                {"11":"Initialization exception. Check if cloud storage has been initialized."},
                {"12":"store_mode of the order is received."},
                {"13":"New order is not reflected."},
                {"14":"Order expired."},
                {"20":"Time period when privacy mode is turned on."},
                {"21":"Upload latency. Check the network quality."},
                {"30":"Report the start time of the video."},
                {"31":"Error code for failure to report the start time of the video.","data":"tuya"},
                {"32":"The format of the response is incorrect, because the needUpdate field is missing.","data":"tuya"},
                {"33":"The format of the response is incorrect, because the encryptKey field is missing."},
                {"34":"The format of the response is incorrect, because the encryptKey field exceeds the limit of 64 bytes."},
                {"35":"The encryption key for cloud storage is updated."},
                {"36":"The start time of the video is reported successfully."},
                {"37":"The time when the video starts."},
                {"38":"The time when the video ends."},
                {"40":"Linkage-triggered action on cloud storage."},
                {"41":"Initialization exception. Check if cloud storage has been initialized."},
                {"42":"The linkage-triggered video recording exceeds the duration limit."},
                {"43":"No status of the cloud storage order is found."},
                {"44":"Privacy mode is on."},
                {"45":"The memory space is insufficient. Check the remaining memory."},
                {"46":"Image capture exception. Check the relevant interface."},
                {"47":"Failed to add a cloud storage event. Check if the relevant interface is called frequently."},
                {"48":"Failed to encrypt the captured image."},
                {"49":"A linkage event is triggered successfully."},
                {"50":"The time when the cloud storage event is triggered locally."},
                {"51":"Failed to add a cloud storage event. Check if the relevant interface is called frequently."},
                {"52":"Failed to upload the image. Check the network health."},
                {"53":"Failed to encrypt the captured image."},
                {"54":"The ID of cloud storage end event"},
                {"55":"The time when the cloud storage event is triggered locally."},
                {"56":"An event of the same type is added repeatedly. Check if the event start interface is called repeatedly."},
                {"57":"Failed to add a cloud storage event. Check if the relevant interface is called frequently."},
                {"58":"Failed to upload the image. Check the network health."},
                {"59":"A cloud storage event ends."},
                {"60":"The start time when a shard is uploaded."},
                {"61":"The size of the uploaded shard."},
                {"62":"Error code for upload failure. Check the network health.","data":"tuya"},
                {"70":"The time when the cloud storage configuration is updated."},
                {"71":"Failed to retrieve cloud storage configuration. No device order found on the cloud.","data":"tuya"},
                {"72":"The obtained order mode."},
                {"73":"Cloud service provider"},
                {"74":"The order is updated."}
            ]
        },
        {"name":"p2p_mod",
            "logseq":[
                {"1":"Failed to get the P2P auth information."},
                {"2":"The type of the current P2P."},
                {"3":"P2P 2.0 initial status."},
                {"4":"P2P 3.0 initial status."},
                {"5":"Failed to create a video talk thread. Check if the system can create a thread."},
                {"6":"Failed to create a detection talk. Check if the system can create a thread."},
                {"7":"P2P initialization is finished."},
                {"11":"P2P 2.0 session listen status."},
                {"12":"P2P 2.0 session authentication failure."},
                {"13":"P2P 2.0 sessions reach the limit. Check if too many apps are streaming simultaneously."},
                {"14":"P2P 2.0 session sending thread failed to be created. Check if the system can create a thread."},
                {"15":"P2P 2.0 session protocol parsing thread failed to be created. Check if the system can create a thread."},
                {"16":"P2P 3.0 session listen status."},
                {"17":"P2P 3.0 session authentication failed."},
                {"18":"P2P 3.0 sessions reach the limit. Check if too many apps are streaming simultaneously."},
                {"19":"P2P 3.0 sending thread failed to be created. Check if the system can create a thread."},
                {"20":"P2P 3.0 protocol parsing thread failed to be created. Check if the system can create a thread."},
                {"21":"Playback query exception."},
                {"22":"Live streaming request."},
                {"23":"Playback request."},
                {"24":"Audio command."},
                {"25":"Switch between definition modes."},
                {"30":"Local video is downloaded."},
                {"31":"Mark the entry to the media transmission thread."},
                {"32":"Send the first I-frame or mark the frame every 30 I-frame."},
                {"33":"Mark audio data transmission."},
                {"34":"Mark the exit from the media transmission thread."},
                {"41":"The entry point to session exit."},
                {"42":"Session is exited."},
                {"43":"Turn on privacy mode."},
                {"44":"Proactively close all the sessions."},
                {"45":"Quit"}
            ]
        },
        {"name":"preset",
            "logseq":[
                {"1":"Add the ID of a preset point."},
                {"2":"Exception with calling http_gw_ipc_preset_add.","data":"tuya"},
                {"11":"The size of the added preset point image."},
                {"12":"Failed to get the CA certificate."},
                {"13":"Exception with the image transfer interface cloud_put_data_to_file.","data":"tuya"},
                {"21":"Exception with calling http_gw_ipc_preset_del.","data":"tuya"},
                {"31":"Synchronize the preset point information with the server."},
                {"32":"Exception with calling http_gw_ipc_preset_get.","data":"tuya"},
                {"33":"Exception with the return value sent from the server.","data":"tuya"}
             ]
        },
        {"name":"notify",
            "logseq":[
                {"1":"Failed to upload the motion image. Check for parameter validity, push frequency, and network health according to the error message."},
                {"2":"The size of the motion image."},
                {"3":"The start time when the motion image is uploaded."},
                {"10":"Failed to call the doorbell. Check for parameter validation and network health according to the error message."},
                {"11":"The size of the doorbell image."},
                {"13":"Failed to report the doorbell message. Check for memory space and network health according to the error message."},
                {"14":"The start time when the doorbell image is uploaded."},
                {"20":"DP 185 data reporting failure. Check for parameter validity, push frequency, memory space, and network health according to the error message."},
                {"21":"DP 185 image reporting failure. Check for parameter validation and memory space according to the error message."},
                {"22":"The timestamp when DP 185 image reporting happens."},
                {"200":"The count of memory allocation messages."},
                {"201":"The size of allocated memory when memory allocation failed. Check the remaining memory."},
                {"202":"The size of the memory allocation."},
                {"210":"Data upload error. Check for parameter validation and network health according to the error message."},
				{"211":"Failed to get the storage configuration. Check the network health."},
                {"212":"The interval between the current time and the last time the configuration was obtained."},
                {"215":"Failed to push resources. Check for parameter validation and network health according to the error message."},
                {"216":"Whether the resource is an image."},
                {"220":"DP 115 alert message reporting failure. See the error message for troubleshooting."},
                {"221":"DP 185 and DP 212 alert message reporting failure. See the error message for troubleshooting."}
            ]
        },
		
        {"name":"stream_stg",
            "logseq":[
                {"1":"tuya_ipc_ss_init called successfully"},
                {"2":"The latest status of the SD card."},
                {"3":"The storage mode is set to none because of an exception with the SD card status."},
                {"4":"__tuya_ipc_ss_init_real return value","data":"tuya"},
                {"5":"ss_init property, string type"},
                {"6":"The size of the memory allocation for media caches."},
                {"20":"start event property, string type"},
                {"21":"stop event property, string type"},
                {"22":"__start_event_storage  Recording start time."},
                {"23":"__start_event_storage  Failed to start recording."},
                {"24":"__stop_event_storage  Failed to stop recording. The path is not writable."},
                {"25":"_stop_event_storage  Recording end time."},
                {"26":"__stop_event_storage  Rename the current_time of the folder."},
                {"27":"ss_put_fram, string type"},
                {"28":"ss_put_fram, string type"},
                {"40":"_update_slice_file_name  The duration of the generated file is a negative number to record the current time."},
                {"50":"Failed to delete the file."}
            ]
        },
		
        {"name":"echoshow",
            "logseq":[
                {"1":"ECHOSHOW_START property, string type"},
                {"2":"ECHOSHOW_TASK property, string type"},
                {"3":"ECHOSHOW_CONNECT_SERVER property, string type"},
                {"4":"ECHOSHOW_SEND_OPTION property, string type"}
            ]
        },
		
        {"name":"chromecast",
            "logseq":[
                {"1":"CHROMECAST_START property, string type"},
                {"2":"CHROMECAST_TASK property, string type"},
                {"3":"CHROMECAST_CREATE_ENV property, string type"}
            ]
        },
		
        {"name":"lowpower",
            "logseq":[
                {"1":"Start"},
                {"2":"Failed to start the service."}
            ]
        }
    ]
}
